<!-- Footer START-->
<div class="footer">
	<div class="footer-topbg">
        <div class="your-personal-button" style="cursor:hand"><img src="themes/default/images/your-personal-guide.png" alt="" style="border:0px;" id="your-personal-button" /></div>
    </div>
<!-- Footer Middle START-->
<?php echo $this->partial('partials/advance_search.phtml'); ?>
<!-- Footer Middle END-->
	<div class="footer-bottombg">
        <div class="footerlink">
            Copyright &copy; 2010 GoPogo LLC<a href="<?php echo GP_ToolKit::getSeoUrl($baseUrl.'/index/about'); ?>">About Us </a>|<a href="<?php echo GP_ToolKit::getSeoUrl($baseUrl.'/index/contact'); ?>">Contact Us</a>|<a href="<?php echo GP_ToolKit::getSeoUrl($baseUrl.'/index/legal'); ?>">Legal</a>
        </div>
    </div>
</div>
<!-- Footer START-->

<!-- Footer Middle START-->
<?php 
echo $this->partial('partials/login.phtml');
echo $this->partial('partials/forgot.phtml');
echo $this->partial('partials/signup.phtml');
echo $this->partial('partials/message.phtml');
?>
<!-- Footer Middle END-->
<script type="text/javascript" src="<?php echo rtrim(Zend_Controller_Front::getInstance()->getBaseUrl(),'/'); ?>/js/jquery-1.4.2.js"></script>
<script type="text/javascript" src="<?php echo rtrim(Zend_Controller_Front::getInstance()->getBaseUrl(),'/'); ?>/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo rtrim(Zend_Controller_Front::getInstance()->getBaseUrl(),'/'); ?>/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?php echo rtrim(Zend_Controller_Front::getInstance()->getBaseUrl(),'/'); ?>/js/jquery.ui.mouse.js"></script>
<script type="text/javascript" src="<?php echo rtrim(Zend_Controller_Front::getInstance()->getBaseUrl(),'/'); ?>/js/jquery.ui.draggable.js"></script>
<script type="text/javascript" src="<?php echo rtrim(Zend_Controller_Front::getInstance()->getBaseUrl(),'/'); ?>/js/lightbox.js"></script>
<script type="text/javascript" src="<?php echo rtrim(Zend_Controller_Front::getInstance()->getBaseUrl(),'/'); ?>/js/main.js"></script>

<script language="javascript" >

// set appl;ication configurations
var app = [];
app.gopogo = [];
// base url of the site
app.gopogo.baseurl = '<?php echo rtrim(Zend_Controller_Front::getInstance()->getBaseUrl()); ?>/';

<?php

$gpConfigs = new Zend_Config_Ini(APPLICATION_PATH . "/configs/application.ini", 'GOPOGO');
// gopogo.debug.default
// debug mode on:1 off:0
// print_r($gpConfigs);
?>
app.gopogo.debug = <?php echo $gpConfigs->gopogo->debug->default ?>;

</script>
</body>
</html>