<!-- Footer START--> 

<div class="footer">
	<div class="footer-topbg">
        <div class="your-personal-button" style="cursor:hand"><img src="<?php echo $baseUrl; ?>/themes/default/images/your-personal-guide.png" alt="" style="border:0px;" id="your-personal-button" />
             <div id="personalArrow" class="arrow-down"></div>
        </div>
       
    </div>
<!-- Footer Middle START-->
<?php echo $this->partial('partials/advance_search.phtml'); ?>
<!-- Footer Middle END-->
	<div class="footer-bottombg">
        <div class="footerlink">
            Copyright &copy; 2010 GoPogo LLC<a href="<?php echo GP_ToolKit::getSeoUrl($baseUrl.'/about'); ?>">About Us </a>|<a href="<?php echo GP_ToolKit::getSeoUrl($baseUrl.'/contact'); ?>">Contact Us</a>|<a href="<?php echo GP_ToolKit::getSeoUrl($baseUrl.'/legal'); ?>">Legal</a>
        </div>
    </div>
</div>
<!-- Footer START-->
<?php
 $config = new Zend_Config_Ini(APPLICATION_PATH . "/configs/application.ini",'GOPOGO');
 $baseUrl = $config->gopogo->url->base;
?>
<!-- Footer Middle START-->
<!--Forgot Password START-->
<?php
    $config = new Zend_Config_Ini(APPLICATION_PATH . "/configs/application.ini",'GOPOGO');
    $baseUrl = $config->gopogo->url->base;
?>
<!--div  id="forgotBox" >
<div class="create-forgot-box" >
                <div class="create-ac-head">
                    <div class="create-ac-leftbg"></div>
                    <div class="sign-in-middlebg">
                    	<div class="create-ac-head-txt">Forgot <b>Password?</b></div>
                    </div>
                    <div class="create-ac-rightbg">
                        <div class="forgot-close-but clsForgotClose"></div>
                    </div>
                </div>
                <div class="sign-in-centerbg">
                    <div class="forgot-box">
                         <form action="" id="forgotBoxForm" name="forgotBoxForm" method="post">
                    	<div class="create-ac-input1"><input type="text" value="Email Address" onclick="if(this.value=='Email Address') {this.value = ''}" onblur="if(this.value=='') {this.value = 'Email Address'}" onkeypress="if(this.value=='Email Address') {this.value = ''}" name="email" class="clsForgotEmail"/></div>
                    	<div class="forgot-txt">Type the characters you see in the picture below.. </div>
                        <div class="forgot-row-mid" >
                            <div class="forgot-row-m1"><img id="imageCaptcha"  /> </div>
                            <div class="forgot-row-m2"><input type="text" name="captcha" id="captcha-form" /></div>
                            <div class="forgot-row-m3" id="forgotSubmitBox"></div>
                       </div>
                         </form>
                    </div>
                </div>
                <div class="sign-in-bottombg"></div>
            </div>
   </div-->
<!--Forgot Password END-->
<?php 
echo $this->partial('partials/login.phtml');
echo $this->partial('partials/forgot.phtml',array('baseUrl'=>$baseUrl));
echo $this->partial('partials/signup.phtml');
echo $this->partial('partials/message.phtml');
?>
<!-- Footer Middle END-->
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery-1.4.2.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.ui.mouse.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.ui.draggable.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/lightbox.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/main.js"></script>

<script language="javascript" >

// set appl;ication configurations
var app = [];
app.gopogo = [];
// base url of the site
app.gopogo.baseurl = '<?php echo rtrim($baseUrl) ?>/';

<?php

$gpConfigs = new Zend_Config_Ini(APPLICATION_PATH . "/configs/application.ini", 'GOPOGO');
// gopogo.debug.default
// debug mode on:1 off:0
// print_r($gpConfigs);
?>
app.gopogo.debug = <?php echo $gpConfigs->gopogo->debug->default ?>;

</script>
</body>
</html>