<!-- Footer START-->
<?php
 $config = new Zend_Config_Ini(APPLICATION_PATH . "/configs/application.ini",'GOPOGO');
 $baseUrl = $config->gopogo->url->base;
?>
<div class="footer">
	<div class="footer-topbg">
        <div class="your-personal-button" style="cursor:hand"><img src="<?php echo $baseUrl; ?>/themes/default/images/your-personal-guide.png" alt="" style="border:0px;" id="your-personal-button" />
             <div id="personalArrow" class="arrow-down"></div>
        </div>

    </div>
<!-- Footer Middle START-->
<?php echo $this->partial('partials/advance_search.phtml'); ?>
<!-- Footer Middle END-->
	<div class="footer-bottombg">
        <div class="footerlink">
            Copyright &copy; <?php echo(date('Y')); ?> GoPogo LLC<a href="<?php echo GP_ToolKit::getSeoUrl($baseUrl.'/about'); ?>">About Us </a>|<a href="<?php echo GP_ToolKit::getSeoUrl($baseUrl.'/contact'); ?>">Contact Us</a>|<a href="<?php echo GP_ToolKit::getSeoUrl($baseUrl.'/legal'); ?>">Legal</a>
        </div>
    </div>
</div>
<!-- Footer START-->

<!-- Footer Middle START-->
<?php

echo $this->partial('partials/login.phtml');
echo $this->partial('partials/forgot.phtml',array('baseUrl'=>$baseUrl));
echo $this->partial('partials/signup.phtml');
echo $this->partial('partials/message.phtml');
echo $this->partial('partials/create_playlist_popup.phtml');

?>
<!-- Footer Middle END-->
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery-1.4.2.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.ui.widget.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.ui.mouse.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.ui.draggable.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.ajaxLoader.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/lightbox.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/main.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/profile.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/create.playlist.js"></script>
<!--<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.rating.js"></script>
<script type="text/javascript" src="<?php echo $baseUrl; ?>/js/jquery.MetaData.js"></script>-->

<script language="javascript" >

// set appl;ication configurations
var app = [];
app.gopogo = [];
// base url of the site
app.gopogo.baseurl = '<?php echo rtrim($baseUrl) ?>/';

<?php

//$gpConfigs = new Zend_Config_Ini(APPLICATION_PATH . "/configs/application.ini", 'GOPOGO');
// gopogo.debug.default
// debug mode on:1 off:0
// print_r($gpConfigs);
?>
app.gopogo.debug = <?php echo $config->gopogo->debug->default ?>;

</script>


<div id="fb-root"></div>
<?php
$fbIds = new Zend_Config_Ini(APPLICATION_PATH . "/configs/application.ini",'facebook');
?>
<script>
    window.fbAsyncInit = function() {
        FB.init({
                appId: <?php echo $fbIds->facebook->appid; ?>,
                status: true,
                cookie: true,
                xfbml: true
            });
    };
    (function() {
        var e = document.createElement('script'); e.async = true;
        e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
        document.getElementById('fb-root').appendChild(e);
    }());
</script>

</body>
</html>