<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');
$this->headMeta()->appendName('keywords', 'Gopogo, Event, Playlist');
$this->headMeta()->appendName('description', 'Gopogo, Event, Playlist');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('GOPOGO');
//echo $this->doctype(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headMeta(); ?>

<?php echo $this->headTitle(); ?>

<?php
/*
$Asset::add_css('/themes/default/css/skin.css');
$Asset::add_css('/themes/default/css/lightbox.css');
$Asset::load_css();

$Asset::add_js('/js/jquery-1.4.2.js');
$Asset::add_js('/js/jquery.ui.core.js');
$Asset::load_js();
*/
?>

<link href="<?php echo rtrim(Zend_Controller_Front::getInstance()->getBaseUrl(),'/'); ?>/themes/default/css/skin.css" rel="stylesheet" type="text/css" />
<link href="<?php echo rtrim(Zend_Controller_Front::getInstance()->getBaseUrl(),'/'); ?>/themes/default/css/lightbox.css" rel="stylesheet" type="text/css" />
</head>
<?php
 $config = new Zend_Config_Ini(APPLICATION_PATH . "/configs/application.ini",'GOPOGO');  
 $basePath = $config->gopogo->url->base;            
?>
<body >
    <?php

        $session = GP_GPAuth::getSession();
        // user_id
        // user_name
        //print_r($session->user_emailid);

        $loginFlag = false;
        $user_name = '';
        if(!empty($session) && !empty($session->user_id) && $session->user_id>0)
        {
            $loginFlag = true;
            $user_name = $session->user_name;
        }
      $baseurl = rtrim(Zend_Controller_Front::getInstance()->getBaseUrl(),'/');

      if(empty($baseurl)) {
          $baseurl = "#";
      }

    ?>
    <div id="master" align="center">
	<div id="submaster">
            <!-- Header START-->     
            <div class="header">
                <div class="head-mainbg">
                    <div>
                    <a class="logo" href="<?php echo $basePath; ?>" title="gopogo" ></a>
                    </div>                        
                        <div class="topmenu">      
                            <?php if($loginFlag){ ?>
                            Welcome, <?php echo ucfirst($user_name); ?> |
                            <a href="#" id='logout' >Logout</a> |
                            <?php } else { ?>
                            <!--Welcome, Guest | -->
                            <a href="javascript:void(0)" class='clsSignIn' >Sign in</a> or
                            <a href="javascript:void(0)" class='clsSignUp' >Create an Account</a> |
                            <?php } ?>
                            <a href="/index/howitworks">How it works</a>

                     </div>
                </div>
                <div class="headrow2">
                    <div class="menu">
                        <div class="menu1"><a href="#"></a></div>
                        <div class="menu2"><a href="#"></a></div>
                        <div class="menu3"><a href="#"></a></div>
                        <div class="menu4"><a href="#"></a></div>
                    </div>
                    <div class="search"><input type="text" value="Search for..."/></div>
                    <div class="search_01"><input type="text" value="City, State, and Zip"/></div>
                    <div class="submenu">
                        <div class="submenu-box">
                            <div class="submenu-left"></div>
                            <div class="submenu-middle"><a href="#">My Profile</a></div>
                            <div class="submenu-right"></div>
                        </div>
                        <div class="submenu-box">
                            <div class="submenu-left"></div>
                            <div class="submenu-middle"><a href="#">My Preferences</a></div>
                            <div class="submenu-right"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <!-- Header END-->


                <?php if (count($this->messages)) : ?>
                <ul id="messages">
                <?php foreach ($this->messages as $message) : ?>
                    <li><?php echo $this->escape($message); ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>
