<div style="height:150px;"></div>
<!--  Body START-->
<div class="container" >
 <!--
    <div class="wraptocenter">
        <span></span><img src="<?php echo $this->baseUrl();?>/themes/default/images/coming_soon.png" height="150px" alt="...">
    </div>
    -->
    <div class="con-box" >
       <div class="con-left" style="width:99%">
     
            <div class="con-left-row1">
                <div class="head-txt">Contact</div>
            </div>
            <div class="coming-soon">
                  <span></span><img src="<?php echo $this->baseUrl();?>/themes/default/images/coming_soon.png" height="150px" alt="...">
            </div>
        </div>
    </div> 
</div>
<!--  Body END-->
<div class="blankdiv"> </div>
