<div class="clsBlankDiv" style="height:150px;"></div>
<!--  Body START-->
         <div class="contenter" align="center">
        	<div class="con-box" align="center">
<!--Left Part start-->
            	<div class="con-left">
                	<div class="con-left-bg">
                    	<span class="con-left-head-txt">Featured Playlists</span>
                        <span class="con-left-link-txt"><a href="#">See all</a></span>
                    </div>
<!--  Featured Playlists START -->
                    <div class="Featured-list">
                    	<div class="arrow-buton"></div>
                    	<div>
                          <!--  Thum img START-->
                                <div class="thum-img-box">
                                  <div class="thum-txt"><span>Billy Idol’s Day in LA</span></div>
                                  <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                  <a href="#"><div class="doit-button"></div></a>
                                        <div class="star-button">
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-grey"></div>
                                            <div class="star-button-grey"></div>
                                        </div>
                                        <div class="interest-button"><a href="#"></a></div>
                                        <div class="link-txt"><span>Brought to you by <br /><a href="#">MGM records</a></span></div>
                                </div>
                          <!--  Thum img END-->
                          <!--  Thum img START-->
                                <div class="thum-img-box">
                                        <div class="thum-txt"><span>Melrose Place</span></div>
                                        <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                        <a href="#"><div class="doit-button"></div></a>
                                        <div class="offer-icon">25%<br /><span style="line-height:0px;">off</span></div>
                                        <div class="star-button">
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-grey"></div>
                                            <div class="star-button-grey"></div>
                                        </div>
                                        <div class="interest-button"><a href="#"></a></div>
                                </div>
                          <!--  Thum img END-->
                          <!--  Thum img START-->
                                <div class="thum-img-box">
                                        <div class="thum-txt"><span>Coca-Cola day on<br />Santa Monica Beach</span></div>
                                        <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                        <a href="#"><div class="doit-button"></div></a>
                                        <div class="star-button">
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-grey"></div>
                                            <div class="star-button-grey"></div>
                                        </div>
                                        <div class="interest-button"><a href="#"></a></div>
                                        <div class="link-txt"><span>Brought to you by <br /><a href="#">MGM records</a></span></div>
                                </div>
                          <!--  Thum img END-->
                          <!--  Thum img START-->
                                <div class="thum-img-box">
                                        <div class="thum-txt"><span>Flight of the Concords<br>Music Festival Parade</span></div>
                                        <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                        <a href="#"><div class="doit-button"></div></a>
                                        <div class="star-button">
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-grey"></div>
                                            <div class="star-button-grey"></div>
                                        </div>
                                        <div class="interest-button"><a href="#"></a></div>
                                </div>
                          <!--  Thum img END-->
                        </div>
                    	<div class="arrow-buton1"></div>
                    </div>
<!--  Featured Playlists START -->
                    <div class="con-left-bg">
                        <span class="con-left-head-txt">Recommendations</span>
                        <span class="dropdown-bg"></span>
                        <span class="con-left-link-txt"><a href="#">See all</a></span>
                    </div>
					<div class="Recom-list">
                        <div class="arrow-buton"></div>
                        <div>
                          <!--  Thum img START-->
                                <div class="thum-img-box">
                                        <div class="thum-txt"><span>A Walk in the Park</span></div>
                                        <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                        <a href="#"><div class="doit-button"></div></a>
                                        <div class="star-button">
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-grey"></div>
                                            <div class="star-button-grey"></div>
                                        </div>
                                        <div class="interest-button"><a href="#"></a></div>
                                        <div class="link-txt"><span>Brought to you by <br /><a href="#">MGM records</a></span></div>
                                </div>
                          <!--  Thum img END-->
                          <!--  Thum img START-->
                                <div class="thum-img-box">
                                        <div class="thum-txt"><span>Sunset on the beach</span></div>
                                        <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                        <a href="#"><div class="doit-button"></div></a>
                                        <div class="star-button">
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-grey"></div>
                                            <div class="star-button-grey"></div>
                                        </div>
                                        <div class="interest-button"><a href="#"></a></div>
                                </div>
                          <!--  Thum img END-->
                          <!--  Thum img START-->
                                <div class="thum-img-box">
                                        <div class="thum-txt"><span>Famous Celebrity<br />First Date Nights</span></div>
                                        <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                        <a href="#"><div class="doit-button"></div></a>
                                        <div class="star-button">
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-grey"></div>
                                            <div class="star-button-grey"></div>
                                        </div>
                                        <div class="interest-button"><a href="#"></a></div>
                                        <div class="link-txt"><span>Brought to you by <br /><a href="#">MGM records</a></span></div>
                                </div>
                          <!--  Thum img END-->
                          <!--  Thum img START-->
                                <div class="thum-img-box">
                                        <div class="thum-txt"><span>Ohhh la la!</span></div>
                                        <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                        <a href="#"><div class="doit-button"></div></a>
                                        <div class="star-button">
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-yellow"></div>
                                            <div class="star-button-grey"></div>
                                            <div class="star-button-grey"></div>
                                        </div>
                                        <div class="interest-button"><a href="#"></a></div>
                                </div>
                          <!--  Thum img END-->
                        </div>
                        <div class="arrow-buton1"></div>
                    </div>
                </div>
 <!--Left Part END-->
 <!-- Right part Start  -->
            	<div class="con-right">
                	<div class="con-right-bg"><span class="con-left-head-txt1">Places You’ll Love</span></div>
                    <div class="con-right-ro1">
                    	<div class="heading-txt">How Well We Know You</div>
                        <div><img src="/themes/default/images/bar.jpg" alt=""/></div>
                        <div class="bar-bottom-txt">Save your progress <a href="javascript:void(0)" class="clsSignIn">Sign in</a>&nbsp;or&nbsp;<a href="javascript:void(0)" class="clsSignUp">Create account</a></div>
                    </div>
                    <div class="con-right-ro2">
                            <div class="heading-txt">What is your favorite movie genre?</div>
                            <div class="radio-button">

                                <div style="display:table-row;" ><span style="display:table-cell;vertical-align:top;" ><input type="radio" name="movieGenre" id="movieGenre" ></span><span style="display:table-cell;margin-bottom: 5px" >&nbsp;Romance</span></div>
                                <div style="display:table-row;" ><span style="display:table-cell;vertical-align:top;" <input type="radio" name="movieGenre" id="movieGenre" ></span><span>&nbsp;Comedy</span></div>
                                <div style="display:table-row;" ><span style="display:table-cell;vertical-align:top;" <input type="radio" name="movieGenre" id="movieGenre" ></span><span>&nbsp;Action</span></div>
                                <div style="display:table-row;" ><span style="display:table-cell;vertical-align:top;" <input type="radio" name="movieGenre" id="movieGenre" ></span><span>&nbsp;Fantasy</span></div>

                            </div>
                            <div class="skip-txt"><a href="#">Skip</a>&nbsp;</div>
                            <div class="radio-button-right"></div>
                    </div>
                    <div class="con-right-row4">
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                    </div>
  <!-- Right part end  -->
                </div>
      		</div>
     	</div>
 <!--  Body END-->
<div class="blankdiv"></div>
