<div class="clsBlankDiv" style="height:150px;"></div>
<!--  Body START-->
         <div class="contenter" align="center">
        	<div class="con-box" align="center">
<!--Left Part start-->
            	<div class="con-left">
                	<div class="con-left-bg">
                    	<span class="con-left-head-txt">Featured Playlists</span>
                        <span class="con-left-link-txt"><a href="#" onclick="return false">See all</a></span>
                    </div>
<!--  Featured Playlists START -->
                    <div class="Featured-list">
                    	<div class="arrow-buton"></div>
                    	<div class="mthumb-box">
                            <div class="mthum-row">
                                    <div class="thum-txt">Billy Idol’s Day in LA</div>
                                    <div class="thum-txt">Melrose Place</div>
                                    <div class="thum-txt">Coca-Cola day onSanta Monica Beach</div>
                                    <div class="thum-txt">Flight of the Concords Music Festival Parade</div>
                            </div>
                            <div class="mthum-row" >
                                    <div class="thum-img-box" >
                                          <div class="thum-img"><img src="/themes/default/images/thum.png" alt="" /></div>
                                          <a href="#" onclick="return false"><div class="doit-button"></div></a>
                                                <div class="star-button">
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-grey"></div>
                                                    <div class="star-button-grey"></div>
                                                </div>
                                                <div class="interest-button"><a href="#" onclick="return false"></a></div>
                                                <div class="link-txt"><span>Brought to you by <br /><a href="#" onclick="return false">MGM records</a></span></div>
                                   </div>
                                    <div class="thum-img-box">
                                          <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                          <a href="#" onclick="return false"><div class="doit-button"></div></a>
                                                <div class="star-button">
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-grey"></div>
                                                    <div class="star-button-grey"></div>
                                                </div>
                                                <div class="interest-button"><a href="#" onclick="return false"></a></div>
                                                <div class="link-txt"><span>Brought to you by <br /><a href="#" onclick="return false">MGM records</a></span></div>
                                   </div>
                                    <div class="thum-img-box">
                                          <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                          <a href="#" onclick="return false"><div class="doit-button"></div></a>
                                                <div class="star-button">
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-grey"></div>
                                                    <div class="star-button-grey"></div>
                                                </div>
                                                <div class="interest-button"><a href="#" onclick="return false"></a></div>
                                                <div class="link-txt"><span>Brought to you by <br /><a href="#" onclick="return false">MGM records</a></span></div>
                                   </div>
                                    <div class="thum-img-box">
                                          <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                          <a href="#" onclick="return false"><div class="doit-button"></div></a>
                                                <div class="star-button">
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-grey"></div>
                                                    <div class="star-button-grey"></div>
                                                </div>
                                                <div class="interest-button"><a href="#" onclick="return false"></a></div>
                                                <div class="link-txt"><span>Brought to you by <br /><a href="#" onclick="return false">MGM records</a></span></div>
                                   </div>
                            </div>
                        </div>
                    	<div class="arrow-buton1"></div>
                    </div>
<!--  Featured Playlists END -->
                    <div class="con-left-bg">
                        <span class="con-left-head-txt">Recommendations</span>
                        <span class="dropdown-bg">&nbsp;Romance</span>
                        <span class="con-left-link-txt"><a href="#" onclick="return false">See all</a></span>
                    </div>
			<div class="Recom-list">
                        <div class="arrow-buton"></div>
                    	<div class="mthumb-box">
                            <div class="mthum-row">
                                    <div class="thum-txt">A Walk in the Park</div>
                                    <div class="thum-txt">Sunset on the beach</div>
                                    <div class="thum-txt">Famous Celebrity First Date Nights</div>
                                    <div class="thum-txt">Ohhh la la!</div>
                            </div>
                            <div class="mthum-row" >
                                    <div class="thum-img-box" >
                                          <div class="thum-img"><img src="/themes/default/images/thum.png" alt="" /></div>
                                          <a href="#" onclick="return false"><div class="doit-button"></div></a>
                                                <div class="star-button">
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-grey"></div>
                                                    <div class="star-button-grey"></div>
                                                </div>
                                                <div class="interest-button"><a href="#" onclick="return false"></a></div>
                                                <div class="link-txt"><span>Brought to you by <br /><a href="#" onclick="return false">MGM records</a></span></div>
                                   </div>
                                    <div class="thum-img-box">
                                          <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                          <a href="#" onclick="return false"><div class="doit-button"></div></a>
                                                <div class="star-button">
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-grey"></div>
                                                    <div class="star-button-grey"></div>
                                                </div>
                                                <div class="interest-button"><a href="#" onclick="return false"></a></div>
                                                <div class="link-txt"><span>Brought to you by <br /><a href="#" onclick="return false">MGM records</a></span></div>
                                   </div>
                                    <div class="thum-img-box">
                                          <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                          <a href="#" onclick="return false"><div class="doit-button"></div></a>
                                                <div class="star-button">
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-grey"></div>
                                                    <div class="star-button-grey"></div>
                                                </div>
                                                <div class="interest-button"><a href="#" onclick="return false"></a></div>
                                                <div class="link-txt"><span>Brought to you by <br /><a href="#" onclick="return false">MGM records</a></span></div>
                                   </div>
                                    <div class="thum-img-box">
                                          <div class="thum-img"><img src="/themes/default/images/thum.png" alt=""/></div>
                                          <a href="#" onclick="return false"><div class="doit-button"></div></a>
                                                <div class="star-button">
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-yellow"></div>
                                                    <div class="star-button-grey"></div>
                                                    <div class="star-button-grey"></div>
                                                </div>
                                                <div class="interest-button"><a href="#" onclick="return false"></a></div>
                                                <div class="link-txt"><span>Brought to you by <br /><a href="#" onclick="return false">MGM records</a></span></div>
                                   </div>
                            </div>
                        </div>
                        <div class="arrow-buton1"></div>
                    </div>
                </div>
 <!--Left Part END--> 
 <!-- Right part Start  -->
            <?php $sessionFlg = $_SESSION['sessionFlg']; ?>
            	<div class="con-right">
                	<div class="con-right-bg"><span class="con-left-head-txt1">Places You’ll Love</span></div>
                        <div class="con-right-ro1" <?php if($sessionFlg) { echo("style='height:250px'"); } ?> >
                    
                    <?php if(empty($sessionFlg)) { ?>
                    	<div class="heading-txt">How Well We Know Youecho </div>
                        <div><img src="/themes/default/images/bar.jpg" alt=""/></div>
                        <div class="bar-bottom-txt">Save your progress <a href="javascript:void(0)" class="clsSignIn">Sign in</a>&nbsp;or&nbsp;<a href="javascript:void(0)" class="clsSignUp">Create account</a></div>
                        <?php } else { ?>
                            <div class="heading-txt">YOUR PROFILE </div>
                            <div><img src="/themes/default/images/bar.jpg" alt=""/></div>

                               <div class="heading-txt">
                                <div style="height:15px;text-align:top;padding: 0px;margin: 0px"><div style="float:left" ><img alt="" src="/themes/default/images/face-icon.jpg"></div><div style="float:left;font-size:13px;padding-bottom:20px">&nbsp;&nbsp;Connect with Facebook.</div> </div>
                                <br clear="all" />
                                <span style="clear:both;font-size:11px">Join your Facebook account to GoPogo and invite friends to your playlists.</span>
                                <br clear="all" />
                                <input type="text" value="Facebook id" style="margin-top:10px">
                                <br/>
                                <input type="text" value="Password" style="margin-top:5px"><br/>
                                <input type="image" src="/themes/default/images/addfacebook.png" style="margin-top:5px">
                           </div>
                            <br clear="all" ><br/>
                            <div class="skip-txt" style="padding-top:110px;padding-left:80px" ><a href="#">Skip</a>&nbsp;</div>


                        <?php }  ?>
                    
                    </div>
                    <?php if(empty($sessionFlg)) { ?>
                    <div class="con-right-ro2">
                            <div class="heading-txt">What is your favorite movie genre?</div>
                            <div class="radio-button">
                                <div style="display:table-row;" ><span style="display:table-cell;vertical-align:top;"><input type="radio" name="movieGenre" value="Romance" checked="checked" /></span><span style="display:table-cell;margin-bottom: 5px" >&nbsp;Romance</span></div>
                                <div style="display:table-row;" ><span style="display:table-cell;vertical-align:top;"><input type="radio" name="movieGenre" value="Comedy" /></span><span style="display:table-cell;margin-bottom: 5px">&nbsp;Comedy</span></div>
                                <div style="display:table-row;" ><span style="display:table-cell;vertical-align:top;"><input type="radio" name="movieGenre" value="Action" /></span><span style="display:table-cell;margin-bottom: 5px">&nbsp;Action</span></div>
                                <div style="display:table-row;" ><span style="display:table-cell;vertical-align:top;"><input type="radio" name="movieGenre" value="Fantasy" /></span><span style="display:table-cell;margin-bottom: 5px">&nbsp;Fantasy</span></div>
                            </div>
                            <div class="skip-txt"><a href="#" onclick="return false">Skip</a>&nbsp;</div>
                            <div class="radio-button-right"></div>
                    </div>
                    <?php } else { ?>
                            
                        <?php }  ?>
                    <div class="con-right-row4">
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                    </div>
  <!-- Right part end  -->
                </div>
      		</div>
     	</div>
 <!--  Body END-->
<div class="blankdiv"></div>
