<div style="height:110px;"></div>
<!--  Body START-->
<div class="container" >
    <div class="con-box" >
        <div class="con-left">
            <!--  Featured Playlists START -->
            <div class="con-left-row1">
                <div class="head-txt">Featured Playlists</div>
            </div>
            <div class="con-left-row2">
                <div class="arrow-buton"></div>
                <!--  Thum img START-->
                <div class="thum-img-box">
                    <div class="thum-txt">Billy Idol’s Day in LA</div>
                    <div class="thum-img"><img src="themes/default/images/thum1.jpg" alt=""/></div>
                    <div><a href="#" class="doit-button"></a></div>
                    <div class="star-button">
                        <div class="star-button-yellow"></div>
                        <div class="star-button-yellow"></div>
                        <div class="star-button-yellow"></div>
                        <div class="star-button-grey"></div>
                        <div class="star-button-grey"></div>
                    </div>
                    <div class="interest-button"><a href="#"></a></div>
                    <div class="link-txt">Brought to you by <br /><a>MGM records</a></div>
                </div>
                <!--  Thum img END-->
                <!--  Thum img START-->
                <div class="thum-img-box">
                    <div class="thum-txt">Melrose Place</div>
                    <div class="thum-img"><img src="themes/default/images/thum2.jpg" alt=""/></div>
                    <div><a href="#" class="doit-button"></a></div>

                    <div class="star-button">
                        <div class="star-button-yellow"></div>
                        <div class="star-button-yellow"></div>
                        <div class="star-button-yellow"></div>
                        <div class="star-button-grey"></div>
                        <div class="star-button-grey"></div>
                    </div>
                    <div class="interest-button-over"></div>
                    <div class="link-txt">Brought to you by <br /><a>MGM records</a></div>
                </div>
                <!--  Thum img END-->
                <!--  Thum img START-->
                <div class="thum-img-box">
                    <div class="thum-txt">Coca-cola <br> day in the sun</div>
                    <div class="thum-img"><img src="themes/default/images/thum3.jpg" alt=""/></div>
                    <div><a href="#" class="doit-button"></a></div>

                    <div class="star-button">
                        <div class="star-button-blue"></div>
                        <div class="star-button-blue"></div>
                        <div class="star-button-blue"></div>
                        <div class="star-button-grey"></div>
                        <div class="star-button-grey"></div>
                    </div>
                    <div class="interest-button"><a href="#"></a></div>
                    <div class="link-txt">Brought to you by <br /><a>Coco Cola</a></div>
                </div>
                <!--  Thum img END-->
                <div><a href="#" class="arrow-buton1"></a></div>
            </div>
            <!--  Featured Playlists END -->
            <!--  Recommendations START -->
            <div class="con-left-row1">
                <div class="head-txt">Recommendations</div>
                <div class="dropdown-bg">
<!--                        	<select>
                        <option>Romance</option>
                    </select>
                    -->                     </div>
            </div>
            <div class="con-left-row2">
                <div class="arrow-buton"><img src="themes/default/images/arrow-left.png" alt=""/></div>
                <!--  Thum img START-->
                <div class="thum-img-box">
                    <div class="thum-txt">A Walk in the Park</div>
                    <div class="thum-img"><img src="themes/default/images/thum4.jpg" alt=""/></div>
                    <div><a href="#" class="doit-button"></a></div>

                    <div class="star-button">
                        <div class="star-button-yellow"></div>
                        <div class="star-button-yellow"></div>
                        <div class="star-button-yellow"></div>
                        <div class="star-button-grey"></div>
                        <div class="star-button-grey"></div>
                    </div>
                    <div class="interest-button"><a href="#"></a></div>
                    <div class="link-txt">Brought to you by <br /><a>MGM records</a></div>
                </div>
                <!--  Thum img END-->
                <!--  Thum img START-->
                <div class="thum-img-box">
                    <div class="thum-txt">Sunset on the beach</div>
                    <div class="thum-img"><img src="themes/default/images/thum5.jpg" alt=""/></div>
                    <div><a href="#" class="doit-button"></a></div>

                    <div class="star-button">
                        <div class="star-button-yellow"></div>
                        <div class="star-button-yellow"></div>
                        <div class="star-button-yellow"></div>
                        <div class="star-button-grey"></div>
                        <div class="star-button-grey"></div>
                    </div>
                    <div class="interest-button-over"></div>
                    <div class="link-txt">Brought to you by <br /><a>MGM records</a></div>
                </div>
                <!--  Thum img END-->
                <!--  Thum img START-->
                <div class="thum-img-box">
                    <div class="thum-txt">Ohh la la</div>
                    <div class="thum-img"><img src="themes/default/images/thum6.jpg" alt=""/></div>
                    <div><a href="#" class="doit-button"></a></div>

                    <div class="star-button">
                        <div class="star-button-blue"><a href="#"></a></div>
                        <div class="star-button-blue"></div>
                        <div class="star-button-blue"></div>
                        <div class="star-button-grey"></div>
                        <div class="star-button-grey"></div>
                    </div>
                    <div class="interest-button"><a href="#"></a></div>
                    <div class="link-txt">Brought to you by <br /><a>MGM records</a></div>
                </div>
                <!--  Thum img END-->
                <div class="arrow-buton1"><img src="themes/default/images/arrow-right.png" alt=""/></div>
            </div>
            <!--  Recommendations END -->
        </div>
        <div class="con-right">
            <div class="con-right-row1">
                <div class="head-txt1">Places You’ll Love</div>
            </div>
            <div class="con-right-row2">
                <div class="heading-txt">How Well We Know You</div>
                <div><img src="themes/default/images/bar.jpg" alt=""/></div>
                <div class="bar-bottom-txt">Save your progress <a href="javascript:void(0)" class="CLS_sign-in">Sign in&nbsp;</a>or&nbsp;<a href="javascript:void(0)" class="CLS_sign-up">Create account</a></div>
            </div>
            <div class="con-right-row3">
                <div class="heading-txt">What is your favorite movie genre?</div>
                <div class="radio-button">
                    <input type="radio"  value="" checked="checked"/>A.&nbsp;Romance<br />
                    <input type="radio"  value="" />B.&nbsp;Comedy<br />
                    <input type="radio"  value=""/>C.&nbsp;Action<br />
                    <input type="radio"  value=""/>D.&nbsp;Fantasy<br />
                </div>
                <div><a href="#" class="radio-button-right"></a></div>
                <div class="skip-txt"><a href="#" >Skip</a></div>
            </div>
            <div class="con-right-row4">
                <!--  Thumb Box START-->
                <div class="rg-thum-img">
                    <div class="rg-thum-img-cel1"></div>
                    <div class="rg-thum-iconbox">
                        <div class="rg-thum-img-cel22"></div>
                        <div class="rg-thum-img-cel33"></div>
                        <div class="rg-thum-img-cel4">98% Liked</div>
                    </div>
                    <div class="rg-thum-content">
                        <span style="font-size:14px;"><b>Rainbow Bar &amp; Grill</b></span><br />
                        (626) 361-3642<br/>
                        709 N. La Brea Ave, CA 90038<br/>
                        One liner desciption of what the item is and..
                    </div>
                </div>
                <!--  Thumb Box START-->
                <!--  Thumb Box START-->
                <div class="rg-thum-img">
                    <div class="rg-thum-img-cel12"></div>
                    <div class="rg-thum-iconbox">
                        <div class="rg-thum-img-cel2"></div>
                        <div class="rg-thum-img-cel3"></div>
                        <div class="rg-thum-img-cel4">98% Liked</div>
                    </div>
                    <div class="rg-thum-content">
                        <span style="font-size:14px;"><b>Rainbow Bar &amp; Grill</b></span><br />
                        (626) 361-3642<br/>
                        709 N. La Brea Ave, CA 90038<br/>
                        One liner desciption of what the item is and..
                    </div>
                </div>
                <!--  Thumb Box START-->
                <!--  Thumb Box START-->
                <div class="rg-thum-img">
                    <div class="rg-thum-img-cel1"></div>
                    <div class="rg-thum-iconbox">
                        <div class="rg-thum-img-cel22"></div>
                        <div class="rg-thum-img-cel33"></div>
                        <div class="rg-thum-img-cel4">98% Liked</div>
                    </div>
                    <div class="rg-thum-content">
                        <span style="font-size:14px;"><b>Rainbow Bar &amp; Grill</b></span><br />
                        (626) 361-3642<br/>
                        709 N. La Brea Ave, CA 90038<br/>
                        One liner desciption of what the item is and..
                    </div>
                </div>
                <!--  Thumb Box START-->
                <!--  Thumb Box START-->
                <div class="rg-thum-img">
                    <div class="rg-thum-img-cel12"></div>
                    <div class="rg-thum-iconbox">
                        <div class="rg-thum-img-cel22"></div>
                        <div class="rg-thum-img-cel33"></div>
                        <div class="rg-thum-img-cel4">98% Liked</div>
                    </div>
                    <div class="rg-thum-content">
                        <span style="font-size:14px;"><b>Rainbow Bar &amp; Grill</b></span><br />
                        (626) 361-3642<br/>
                        709 N. La Brea Ave, CA 90038<br/>
                        One liner desciption of what the item is and..
                    </div>
                </div>
                <!--  Thumb Box START-->
                <!--  Thumb Box START-->
                <div class="rg-thum-img">
                    <div class="rg-thum-img-cel1"></div>
                    <div class="rg-thum-iconbox">
                        <div class="rg-thum-img-cel2"></div>
                        <div class="rg-thum-img-cel3"></div>
                        <div class="rg-thum-img-cel4">98% Liked</div>
                    </div>
                    <div class="rg-thum-content">
                        <span style="font-size:14px;"><b>Rainbow Bar &amp; Grill</b></span><br />
                        (626) 361-3642<br/>
                        709 N. La Brea Ave, CA 90038<br/>
                        One liner desciption of what the item is and..
                    </div>
                </div>
                <!--  Thumb Box START-->
            </div>
        </div>
    </div>
</div>
<!--  Body END-->
<div class="blankdiv"></div>