<div class="select_area">
    <a href="javascript:void(0)" onclick="backMsgClick()" class="backtomsg_bg clsMsgBack"></a>
    <a href="javascript:void(0)" onclick="" class="select_delete_bg"></a>
</div>

<div class="msg_bg">
    <div class="msgHeading"> Billy idols day in LA  </div> <br/>
    <div class="message_text"> Between You and Dwight Schrute</div>
</div>

<div>
   <div class="white_bg_area">
      <div class="user-image"><img src="/themes/default/images/dummy-image.png" border="0" /></div>
      <div class="firstRowBg"> <div class="white_bg_title1">Dwight Schrute </div>
      <div class="white_bg_gray_text1">October 27</div>
      <div class="white_bg_bluetext1"> Reply: Bill Idol’s Day in LA</div>
      </div>
    </div>
    <div class="replyAreaBg">
        <div class="replyText">replyText</div>
        <div class="replyArea"><textarea>afa</textarea></div>
        <div class="replyBtn"><img src="/themes/default/images/reply.png" border="0"></div>
    </div>
</div>