<div class="select_area">
    <div class="select_all_bg"></div>
    <a href="javascript:void(0)" onclick="backMsgClick()" class="select_delete_bg clsMsgBack"></a>
</div>

<div class="gray_date_subject_bg">
    <div class="white_bg_title1"> Billy idols day in LA  </div> <br/>
    <div class="white_bg_dark_text"> Between You and Dwight Schrute</div>
</div>

<div>
   <div class="white_bg_area">
      <div class="user-image"><img src="/themes/default/images/dummy-image.png" border="0" /></div>
      <div class="firstRowBg"> <div class="white_bg_title1">Dwight Schrute </div>
      <div class="white_bg_gray_text1">October 27</div>
      <div class="white_bg_bluetext1"> Reply: Bill Idol’s Day in LA</div>
      </div>
    </div>
    <div>
        Reply<br/>
        <textarea rows="5" cols="25"></textarea>
        <input type="button" name="" id="" value="Reply"/>
    </div>
</div>