<!--
<div>
    <?php if(sizeof($this->commentArr)>0) {
        foreach ($this->commentArr as $comment) { ?>
        <div style="font-size: 15px">
            <div> <input type="checkbox" onclick=""> image  &nbsp;&nbsp;<b><?php echo $comment['commentAuthor'];?> &nbsp;&nbsp;</b></div>
            <div></div>
            <div>
                <?php echo $comment['comment'];?><br />
            </div>
        </div><div class="rg-thum-content" style="width:83px"></div>
    <?php }
    }
    ?>
    <div>
        Reply<br/>
        <textarea rows="5" cols="25" class="clsReplyMsg"></textarea>
        <input type="button" onclick="doReplyMsg()" name="" id="" value="Reply"/>
    </div>
</div> -->

<div class="gray_date_subject_bg">
    <div class="gray_bg_date_area">Date asf asdf asdf sdasf   </div>
    <div class="black-arrow-bg"></div>
    <div class="gray_bg_subject_area">Subject </div>
    <div class="light-gray-downarrow"></div>
</div>
                
<div class="blue_box_area">
    <div class="white_bg_area">
        <div class="user-image"><img src="/themes/default/images/dummy-image.png" border="0" /></div>
        <div class="firstRowBg"> <div class="white_bg_title1">Dwight Schrute </div>
        <div class="white_bg_gray_text1">October 27</div>
        <div class="white_bg_bluetext1"> Reply: Bill Idol’s Day in LA</div>
        </div>
    </div>
</div>

<div class="light_gray_bor_bg"> &nbsp;</div>

<div class="light_gray_bor_bg"> &nbsp;</div>


<div class="blue_box_area">
    <div class="white_bg_area">
        <div class="user-image"><img src="/themes/default/images/dummy-image.png" border="0" /></div>
        <div class="firstRowBg"> <div class="white_bg_title1">Dwight Schrute </div>
        <div class="white_bg_gray_text1">October 27</div>
        <div class="white_bg_bluetext1"> Reply: Bill Idol’s Day in LA</div>
        </div>
    </div>
</div>
