<div class="select_area">
    <div class="select_all_bg"><input type="checkbox" class="select_all_chk"/></div>
    <div class="select_delete_bg"></div>
    <div class="filter_bg"> <input border="0" type="text" class="filter_area_bg"></div>
</div>

<div class="gray_date_subject_bg">
    <div class="gray_bg_date_area">Date  </div>
    <div class="black-arrow-bg"></div>
    <div class="gray_bg_subject_area">Subject </div>
    <div class="light-gray-downarrow"></div>
</div>

<div class="blue_box_area">
    <div class="white_bg_area">
        <div class="square_bg"></div>
        <div class="white_bg_title">Dwight Schrute</div>
        <div class="white_bg_bluetext"> <a href="javascript:void(0)" onclick="doReplyMsg()">Reply:</a> Bill Idol’s Day in LA</div>
        <div class="second_row_text">
            <div class="white_bg_gray_text">October 27</div>
            <div class="white_bg_dark_text"> Yes:  I’ll be there.  I’m going to be at..</div>
        </div>
    </div>

    <div class="blue_light_bg_area">
        <div class="square_bg1"></div>
        <div class="white_bg_title">Dwight Schrute</div>
        <div class="white_bg_bluetext"> Reply: Bill Idol’s Day in LA</div>
        <div class="second_row_text">
            <div class="white_bg_gray_text">October 27</div>
            <div class="white_bg_dark_text"> Yes:  I’ll be there.  I’m going to be at..</div>
        </div>
    </div>

</div>

<div class="light_gray_bor_bg"> &nbsp;</div>

<div class="light_gray_bor_bg"> &nbsp;</div>


<div class="blue_box_area">
    <div class="blue_light_bg_area">
        <div class="square_bg"></div>
        <div class="white_bg_title">Dwight Schrute</div>
        <div class="white_bg_bluetext"> Reply: Bill Idol’s Day in LA</div>
        <div class="second_row_text">
            <div class="white_bg_gray_text">October 27</div>
            <div class="white_bg_dark_text"> Yes:  I’ll be there.  I’m going to be at..</div>
        </div>
    </div>

    <div class="white_bg_area">
        <div class="square_bg1"></div>
        <div class="white_bg_title">Dwight Schrute</div>
        <div class="white_bg_bluetext"> Reply: Bill Idol’s Day in LA</div>
        <div class="second_row_text">
            <div class="white_bg_gray_text">October 27</div>
            <div class="white_bg_dark_text"> Yes:  I’ll be there.  I’m going to be at..</div>
        </div>
    </div>


</div>

<div class="light_gray_bor_bg"> &nbsp;</div>

<div class="blue_box_area">

    <div class="blue_light_bg_area">
        <div class="square_bg"></div>
        <div class="white_bg_title">Dwight Schrute</div>
        <div class="white_bg_bluetext"> Reply: Bill Idol’s Day in LA</div>
        <div class="second_row_text">
            <div class="white_bg_gray_text">October 27</div>
            <div class="white_bg_dark_text"> Yes:  I’ll be there.  I’m going to be at..</div>
        </div>
    </div>

    <div class="white_bg_area">
        <div class="square_bg1"></div>
        <div class="white_bg_title">Dwight Schrute</div>
        <div class="white_bg_bluetext"> Reply: Bill Idol’s Day in LA</div>
        <div class="second_row_text">
            <div class="white_bg_gray_text">October 27</div>
            <div class="white_bg_dark_text"> Yes:  I’ll be there.  I’m going to be at..</div>
        </div>
    </div>

</div>