<script type="text/javascript">
    
</script>

<div class="clsBlankDiv" style="height:150px;"></div>
<!--  Body START-->
         <div class="contenter" align="center">
        	<div class="con-box" align="center">
<!--Left Part start-->
            	<div class="con-left">                	
                    <div class="con-left-bg">
                        
                    </div>			
                </div>
 <!--Left Part END-->
 <!-- Right part Start  -->
            <?php $session = GP_GPAuth::getSession(); ?>
            	<div class="con-right">
                    <div class="con-right-bg"><span class="con-left-head-txt1">My Info</span></div>
                    <div class="con-right-ro1" style="height:250px">
                            <div class=""><img style="height:75px" alt="" src="/themes/default/images/thum.png"></div>
                            <div class="heading-txt clsDivUN"><?php echo $session->user_name; ?></div><br/>
                            <div class="clsDivUD"><?php echo $session->user_profile_description; ?></div>
                            <div class="clsProAction" ><a href="#" class="clsEUPro"><b>Edit</b></a>&nbsp;</div>
                    </div>
                    <div id="tabs" class="con-right-row4">
                        <ul>
                            <li><a href="#tabs-1">Messages</a>
                            <a href="#tabs-2">Comments</a>
                            <a href="#tabs-3">Photos</a></li>
                        </ul>

                  <!--  Message Box START-->
                  <div class="clsMsgDiv">
                      <?php 
                      if(sizeof($this->msgArr)>0) {
                          foreach($this->msgArr as $rowMsg) { ?>
                            <div>
                                <div class="rg-thum-content" style="width:95px"><b><?php echo $rowMsg['msgAuthor'];?> &nbsp;&nbsp;</b></div>
                                <div class="rg-thum-content" style="padding-left: 10px">
                                    <a href="javascript:void(0)" class="clsMsgId_<?php $rowMsg['msgId']?>" onclick="showMsgDtl()">Reply &nbsp;</a><b><?php echo $rowMsg['msgHead'];?></b><br />
                                    <?php echo $rowMsg['msgComment'];?>...
                                </div>
                            </div><div class="rg-thum-content" style="width:83px"></div>                            
                            <?php }
                      }
                            ?>
                  </div>
                  <div>
                      <input type="button" name="" id="" style="display: none" class="clsBackMsg" value="Back to Messages"/>&nbsp;&nbsp;
                      <input type="button" name="" id="" style="display: none" class="clsDeleteMsg" value="Delete"/>
                      <div class="dtlMsgDiv" style="display:none"></div>
                  </div>
                  <!--  Thumb Box START-->
                    </div>
  <!-- Right part end  -->
                </div>
      		</div>
     	</div>
 <!--  Body END-->
<div class="blankdiv">
    
</div>
