<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Gopogo - Email Update Welcome</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
      <h2>Welcome to GoPogo</h2>
        <p> </p>
      <p>Your gopogo account email has been changed</p>
      <br>
      <p>Your Old Email :</p>
      <br>Your Email : <?php echo $this->oldemail; ?><br>
      <br>
      <p>Your Updated Email Info:</p>
      <br>Your Email : <?php echo $this->email; ?><br>

      <p>Thank you,</p>
      <p><b><i>The GoPogo Team</i></b></p>
    <p style="font-family: 'Helvetica Neue',Arial,Helvetica,sans-serif; margin-top: 5px; font-size: 10px; color: rgb(136, 136, 136);">

      Please do not reply to this message; it was sent from an non-monitored email address. This message is a service email related to your use of GoPogo. For general inquiries or to request support with your GoPogo account, please visit us at GoPogo Support. <a href="<?php echo $this->link;?>" ><?php echo $this->link;?>/support/</a>.
    </p>
  </body>
</html>
