<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Gopogo - Forgot Password</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
      <h1>Gopogo - Forgot Password</h1>
      <h2>Hi <?php echo $this->name; ?></h2>
      <p>You have requested new password!</p>
      <p>Your Email : <?php echo $this->email; ?></p>
      <p>Your New Password : <?php echo $this->temp_password; ?></p>
      <p>So use new password for login</p>
      <p><a href="<?php echo $this->link;?>" ><?php echo $this->link;?></a></p>
      <p>Regards,</p>
      <p>Gopogo Team</p>
      <p><a href="<?php echo $this->link;?>" ><?php echo $this->link;?></a></p>
  </body>
</html>
