<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Gopogo - Password Update</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
      <h2>Forgot your password ,<?php echo $this->name; ?></h2>
      <p>GoPogo received a request for the 'Password Update' for your Gopogo account and hence you have received the new password!</p>
      <br>Below are the details:
      <br>Your Email : <?php echo $this->email; ?>
      <br>Your new password : <?php echo $this->password; ?><br>
      <p>Login below to GoPogo with your new password</p>
      <p><a href="<?php echo $this->link;?>" ><?php echo $this->link;?></a></p>
      <p>Thank you,</p>
      <p>If you don't want to reset your password, please ignore this message. Your password will not be reset. If you have any concerns, please contact us at GoPogo Support. </p>
      <p><b><i>The GoPogo Team</i></b></p>
      <p>
      <p style="font-family: 'Helvetica Neue',Arial,Helvetica,sans-serif; margin-top: 5px; font-size: 10px; color: rgb(136, 136, 136);">

  Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of GoPogo. For general inquiries or to request support with your GoPogo account, please visit us at GoPogo Support. <a href="<?php echo $this->link;?>" ><?php echo $this->link;?>/support/</a>.
</p>

  </body>
</html>
