<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Gopogo-Forgot Password</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
      <h1>Gopogo-Reset Password</h1>
      <h2>Hi <?php echo $this->name; ?></h2>
      <p>You have reset your password!</p>
      <p>Regards,</p>
      <p>Gopogo Team</p>
  </body>
</html>
