<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Gopogo - Signup Welcome</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
      <h2>Welcome to GoPogo</h2>
        <p>      Thanks for joining our team! We look forward helping you to create fun.</p>
      <p>Plan your day and big adventure on tiny budget.  Want to spice up an errand by discovering a tasty restaurant or unique shop in the vicinity? Simply enter your location and how much time or money you want to spend, and GoPogo will instantly generate a "TooDo" List.</p>
       <p>Login Info:</p>
      <br>Your Email : <?php echo $this->email; ?><br>
      <br>Your Password : <?php echo $this->password; ?><br>

      <p>Thank you,</p>
      <p><b><i>The GoPogo Team</i></b></p>
    <p style="font-family: 'Helvetica Neue',Arial,Helvetica,sans-serif; margin-top: 5px; font-size: 10px; color: rgb(136, 136, 136);">

      Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of GoPogo. For general inquiries or to request support with your GoPogo account, please visit us at GoPogo Support. <a href="<?php echo $this->link;?>" ><?php echo $this->link;?>/support/</a>.
    </p>
  </body>
</html>
