<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Gopogo - Signup Welcome</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
      <h2>Welcome to GoPogo</h2>
        <p>      Thanks for joining our team! We look forward helping you to create fun.</p>
      <p>Please confirm your Gopogo account by clicking this link:</p>
      <p><a href="<?php echo $this->confirmLink;?>" target="_blank"><?php echo $this->confirmLink; ?></a><p>
      <p>Once you confirm, you will have full access to Gopogo and all future notifications will</p>
      <p>be sent to this email address.</p>
      <p>Thank you,</p>
      <p><b><i>The GoPogo Team</i></b></p>
    <p style="font-family: 'Helvetica Neue',Arial,Helvetica,sans-serif; margin-top: 5px; font-size: 10px; color: rgb(136, 136, 136);">

      Please do not reply to this message; it was sent from an unmonitored email address. This message is a service email related to your use of GoPogo. For general inquiries or to request support with your GoPogo account, please visit us at GoPogo Support. <a href="<?php echo $this->link;?>" ><?php echo $this->link;?>/support/</a>.
    </p>
  </body>
</html>
