<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Gopogo - Signup Welcome</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
      <h1>Gopogo - Signup Welcome</h1>
      <h2>Hi <?php echo $this->name; ?></h2>
      <p>welcome to you on gopogo!</p>
      <p>Your Login Information</p>
      <p>Your Email : <?php echo $this->email; ?></p>
      <p>Your Password : <?php echo $this->password; ?></p>     
      <p><a href="<?php echo $this->link;?>" ><?php echo $this->link;?></a></p>
      <p>Regards,</p>
      <p>Gopogo Team</p>
      <p><a href="<?php echo $this->link;?>" ><?php echo $this->link;?></a></p>
  </body>
</html>
