<!-- Footer Middle START-->
       <div class="footer-middle" style="display: none;" >
                <div class="footer-control">
                    <div class="footer-cel1">
                         <div class="footer-header-txt">I want to spend</div>
                         <div class="footer-lefticon1"></div>
                         <div class="footer-input-box">
                             <div class="footer-input1"><input type="text" value="" style="width:50px; height:15px;"/></div>
                             <div class="footer-input2"><input type="text" value="" style="width:50px; height:15px;"/></div>
                             <div class="footer-input3"><input type="text" value="" style="width:50px; height:15px;"/></div>
                         </div>
                    </div>
                    <div class="footer-cel2">
                         <div class="footer-header-txt">Something good for</div>
                         <div class="footer-lefticon2"></div>
                         <div class="footer-input-box">
                             <div class="footer-input12"><input type="text" value="" style="height:15px;"/></div>
                             <div class="footer-input12"><input type="text" value="" style="height:15px;"/></div>
                             <div class="footer-input12"><input type="text" value="" style="height:15px;"/></div>
                         </div>
                    </div>
                    <div class="footer-cel3">
                         <div class="footer-header-txt">In this neighborhood</div>
                         <div class="footer-input-box">
                             <div class="footer-input13"><input type="text" value="" style=""/></div>
                             <div class="footer-menu">
                                <div class="footer-white-txt">Glendale</div>
                                <div class="footer-input-option"></div>
                             </div>
                             <div class="footer-menu">
                                <div class="footer-white-txt">Glendale</div>
                                <div class="footer-input-option"></div>
                             </div>
                             <div class="footer-menu">
                                <div class="footer-white-txt">Glendale</div>
                                <div class="footer-input-option"></div>
                             </div>
                         </div>
                    </div>
                </div>
        </div>
<!-- Footer Middle END-->