<!--Forgot password start-->
            <div  id="forgotBox" >
                <div class="create-ac-head" >
                    <div class="sign-in-leftbg"></div>
                    <div class="sign-in-middlebg">
                    	<div class="create-ac-head-txt">Forgot <b>Password</b></div>
                    </div>
                    <div class="sign-in-rightbg"></div>
                    <div class="login-close"></div>
                </div>
                <div class="sign-in-centerbg" id="sign-in-centerbg">
                    <span class="errorMsg" id="errorMsg" ></span>                    
                    <div id="toggleForgot" > 
                        <form action="" id="forgotBoxForm" name="forgotBoxForm" method="post">
                        <div class="sign-in-right">
                            <div class="create-ac-input1"><input type="text" value="Email Address" onclick="if(this.value=='Email Address') {this.value = ''}" onblur="if(this.value=='') {this.value = 'Email Address'}" onkeypress="if(this.value=='Email Address') {this.value = ''}" name="email" class="clsForgotEmail"/></div>
                            <div class="forgot-input2">Type the characters you seen in the picture below.</div>
                            <br clear="all" /><br/>
                            <div class="create-ac-input1"><input type="image" src="" /></div>
                            <br clear="all" /><br/>
                            <div class="create-ac-input1"><input type="text" value="Characters" onclick="if(this.value=='Characters') {this.value = ''}" onblur="if(this.value=='') {this.value = 'Characters'}" onkeypress="if(this.value=='Characters') {this.value = ''}" name="characters" class="clsForgotEmail"/></div>
                            <div class="sign-in-button">&nbsp;<img alt=""  id="forgotSubmitBox" src="<?php echo $this->baseurl;?>/themes/default/images/submit.jpg"/></div>
                        </div>
                       </form>
                    </div>
                </div>
                <div class="sign-in-bottombg"></div>
            </div>
<!--Forgot password end-->