<!--Forgot in START-->
            <div  id="forgotBox" style="display: none;" >
                <form id="forgotBoxForm" name="forgotBoxForm" method="post">
                <div class="create-ac-head">
                    <div class="sign-in-leftbg"></div>
                    <div class="sign-in-middlebg">
                    	<div class="create-ac-head-txt">Sign in to <b>GoPogo</b></div>
                    </div>
                    <div class="sign-in-rightbg">
                        <div class="create-ac-close"></div>
                    </div>
                </div>
                <div class="sign-in-centerbg">
                    <div class="sign-in-right">
                        <span id="error_msg" ></span>
                    	<div class="create-ac-input1"><input type="text" value="Email Address" name="email" /></div>
                    	<div class="create-ac-input3">
                            <div class="create-ac-login Forgot-Your-Password  ">Forgot Your Password</div>
                            <div class="create-ac-txt"> &nbsp; Or &nbsp; </div>
                            <div class="create-ac-login Create-Account ">Create Account</div>
                            <div><img id="loginSubmitBox" src="themes/default/images/sign-in.png"></div>
                        </div>
                        <div class="create-ac-input3">
                            <div class="create-ac-txt">Already have an account</div>
                            <div class="create-ac-login Login">&nbsp;Login?</div>
                            <div class="create-ac-txt"> &nbsp; Or &nbsp; </div>
                            <div class="create-ac-login Create-Account ">Create Account</div>
                            <div class="create-ac-create-but" id="forgotSubmitBox" ></div>
                        </div>
                    	<div class="create-ac-input4"></div>
                    </div>
                </div>
                <div class="sign-in-bottombg"></div>
                </form>
            </div>
<!--Forgot in END-->