<!--Sign in START-->
            <div  id="loginBox" style="display: none;" >
                <div class="create-ac-head">
                    <div class="sign-in-leftbg"></div>
                    <div class="sign-in-middlebg">
                    	<div class="create-ac-head-txt">Sign in to <b>GoPogo</b></div>
                    </div>
                    <div class="sign-in-rightbg">
                        <div class="create-ac-close"></div>
                    </div>
                </div>
                <div class="sign-in-centerbg">
                    <div class="sign-in-right">
                    	<div class="create-ac-input1"><input type="text" value="Email Address" /></div>
                    	<div class="create-ac-input2"><input type="text" value="Password" /></div>
                    	<div class="create-ac-input3">
                            <div class="create-ac-txt">Already have an account</div>
                            <div class="create-ac-login">&nbsp;Login?</div>
                            <div class="create-ac-create-but"></div>
                       </div>
                    	<div class="create-ac-input4"></div>
                    </div>
                </div>
                <div class="sign-in-bottombg"></div>
            </div>
<!--Sign in END-->