<!--Sign in START-->
            <div  id="loginBox" >
                <form id="loginBoxForm" name="loginBoxForm" method="post">
                <div class="create-ac-head" >
                    <div class="sign-in-leftbg"></div>
                    <div class="sign-in-middlebg">
                    	<div class="create-ac-head-txt">Sign in to <b>GoPogo</b></div>
                    </div>
                    <div class="sign-in-rightbg"></div>
                    <div class="login-close"></div>
                </div>
                <div class="sign-in-centerbg" id="sign-in-centerbg">
                    <div class="sign-in-right" valign="top">
                        <span id="error_msg" ></span>
                    	<div class="create-ac-input1"><input type="text" value="Email Address" name="email" /></div>
                    	<div class="create-ac-input2"><input type="password" value="Password"  name="passwd" /></div>
                    	<div class="sign-in-input3">
                                <span class="sign-in-txt">Forgot your</span>
                                <span class="sign-in-create-account">&nbsp;password</span>
                                <span>&nbsp;or&nbsp;</span>
                                <span class="sign-in-create-account" >create account</span>                                
                       </div>                        
                        <div class="sign-in-button">&nbsp;<img id="loginSubmitBox" src="themes/default/images/sign-in.png"></div>
                    	<div class="sign-in-input4"></div>
                    </div>
                </div>
                <div class="sign-in-bottombg"></div>
                </form>
            </div>
<!--Sign in END-->