<!--message in START-->
            <div  id="messageBox" style="display: none;" >
                <form id="messageBoxForm" name="messageBoxForm" method="post">
                <div class="create-ac-head">
                    <div class="sign-in-leftbg"></div>
                    <div class="sign-in-middlebg">
                    	<div class="create-ac-head-txt">Message <b>GoPogo</b></div>
                    </div>
                    <div class="sign-in-rightbg">
                        <div class="create-ac-close"></div>
                    </div>
                </div>
                <div class="sign-in-centerbg">
                    <div class="sign-in-right">
                        <span id="message_error_msg" ></span>
                        <div class="h15 clear" ></div>
                    	<div class="create-ac-input3">
                            <div class="create-ac-txt">Forgot your</div>
                            <div class="create-ac-login">&nbsp;password or create account</div>
                            <div><img id="loginSubmitBox" src="themes/default/images/sign-in.png"></div>
                       </div>
                    	<div class="create-ac-input4"></div>
                    </div>
                </div>
                <div class="sign-in-bottombg"></div>
                </form>
            </div>
<!--message in END-->