<?php
$loginFlag = false;
$fbLogin = "false";
$session = GP_GPAuth::getSession();

if(!empty($session) && !empty($session->user_id) && $session->user_id>0)
    {
        $loginFlag = true;
        $user_name = $session->user_name;
        $fbLogin = "true";
    }
 else {
        // create facebook object
        $facebook = Facebook_FbClass::getConfig();
    }
?>

<!--Create an account START-->
            <div id="signupBox" >
                <form id="signupBoxForm" name="signupBoxForm" method="post">
                <div class="create-ac-head">
                    <div class="create-ac-leftbg"></div>
                    <div class="create-ac-middlebg">
                        <div class="create-ac-head-txt">Create an <b>Account</b></div>
                    </div>
                    <div class="create-ac-rightbg"></div>
                    <div class="create-ac-close"></div>
                </div>
                <div class="create-ac-centerbg">
                    <div class="create-ac-left">
                        <img src="/themes/default/images/create-account-img.jpg"  alt=""/>
                    </div>
                    <div class="create-ac-right">

                        <!-- <span id="signup_error_msg" class="errorMsg1" ></span> -->
                        <div class="create-ac-input1"><input type="text" value="Email Address" maxlength="50" onclick="if(this.value=='Email Address') {this.value = ''}" onblur="if(this.value=='') {this.value = 'Email Address'; $().removeTextColor(this);} else if(this.value == 'Email Address'){ $().removeTextColor(this); } else {$().setTextColor(this);}" onkeypress="if(this.value=='Email Address') {this.value = ''; $().removeTextColor(this);}else{$().setTextColor(this);}" name="email" id="email" class="clsSignUpEmail"/></div>
                        <div class="create-ac-input2">
                            <input type="text" value="Password" maxlength="50" onfocus="$('.clsSignUpPwdOld').attr('style','display:none');$('.clsSignUpPwd').removeAttr('style');$('.clsSignUpPwd').focus()" name="passwd" id="passwd" class="clsSignUpPwdOld"/>
                            <input type="password" value="" maxlength="50" onfocus="$().setTextColor(this);" onblur="if(this.value=='') { $('.clsSignUpPwdOld').removeAttr('style');$('.clsSignUpPwd').attr('style','display:none');}" name="passwd" id="passwd" class="clsSignUpPwd" style="display: none"/>
                        </div>
                        <div class="h15 clear" ></div>
                        <div class="create-ac-input2">
                            <input type="text" value="Re-Type Password" maxlength="50" onfocus="$('.clsSignUpRePwdOld').attr('style','display:none');$('.clsSignUpRePwd').removeAttr('style');$('.clsSignUpRePwd').focus()" name="retype_passwdOld" id="retype_passwdOld" class="clsSignUpRePwdOld"/>
                            <input type="password" value="" maxlength="50" onfocus="$().setTextColor(this);" onblur="if(this.value=='') { $('.clsSignUpRePwdOld').removeAttr('style');$('.clsSignUpRePwd').attr('style','display:none');}" name="retype_passwd" id="retype_passwd" class="clsSignUpRePwd" style="display: none"/>
                        </div>
                     
                        <div class="create-ac-input3">

                            <span class="create-ac-txt">Already have an account&nbsp;</span>
                            <a href="#" onclick="return false;" class="create-ac-login login">Login?</a>
                            <a href="#" class="create-ac-create-but" id="signupSubmitBox" ></a>

                        </div>
                        <div class="create-ac-input4" >
                            <?php if($fbLogin == "false") { echo $facebook->FBLogin(); } ?>
                        </div>
                    </div>
                </div>
                <div class="create-ac-bottombg"></div>
                </form>
            </div>
<!--Create an account END-->