
<div class="select_area">
    <div class="select_all_bg"><input id="selectAll" name="selectAll" type="checkbox" class="select_all_chk" onclick="selAllChk()"/></div>
    <div><a href="javascript:void(0)" onclick="delMsg()" class="clsMsgDel select_delete_bg"></a></div>
    <div class="filter_bg"> <input border="0" type="text" class="filter_area_bg"></div>
</div>

<div class="gray_date_subject_bg">
    <div class="gray_bg_date_area">Playlist  </div>
    <div class="gray_bg_subject_area">Comment </div>
</div>

<?php //if(sizeof($this->msgList)) { $msgId="";
     // foreach($this->msgList as $msg) { $msgId.=$msg['user_message_id'].",";?>

<div class="blue_box_area">
    <div class="white_bg_area">
        <div class="square_bg"><input type="checkbox" name="msgChk" id="msgChk" value="<?php //echo $msg['user_message_id'];?>"/></div>
        <div class="white_bg_title">Billy Idol's Day in LA <?php // echo $msg['user_name']; ?></div>
        <div class="white_bg_bluetext">
           <!-- <a href="#" onclick="doReplyMsg(<?php //echo $msg['user_playlist_sender_id'];?>)"> <?php //if($msg['status_id'] == 6){?> -->
                This looks really fun. I can't wait to visit
                Little Joy's and Vinnies. It's going to be
                crazy. <?php //} ?> <!-- </a> --> <?php //echo $msg['Message_Subject']; ?></div>
        <div class="second_row_text">
            <div class="white_bg_gray_text"><?php //echo $msg['send_date']; ?></div>
            <div class="white_bg_dark_text"><?php //echo $msg['Message_Subject']; ?> </div>
        </div>
    </div>
</div>
<?php // }
 //} ?>
<div class="blue_box_area">
<?php
// echo $this->paging;
?>
</div>
<div class="light_gray_bor_bg"> &nbsp;</div>

<!-- HIDDEN FIELDS ARE DECLAIRED HERE -->
<input type="text" name="hdnChkMsg" id="hdnChkMsg" class="clsHdnChkMsg" value="<?php //echo $msgId; ?>"/>