<script type="tetext/javascript">
    
</script>

<div class="clsBlankDiv" style="height:150px;"></div>
<!--  Body START-->
         <div class="contenter" align="center">
        	<div class="con-box" align="center">
<!--Left Part start-->
            	<div class="con-left">                	
                    <div class="con-left-bg">
                        
                    </div>			
                </div>
 <!--Left Part END-->
 <!-- Right part Start  -->
            <?php $session = GP_GPAuth::getSession(); ?>
            	<div class="con-right">
                    <div class="con-right-bg"><span class="con-left-head-txt1">My Info</span></div>
                    <div class="con-right-ro1" style="height:250px">
                            <div class=""><img style="height:75px" alt="" src="/themes/default/images/thum.png"></div>
                            <div class="heading-txt clsDivUN"><?php echo $session->user_name; ?></div><br/>
                            <div class="clsDivUD"><?php echo $session->user_profile_description; ?></div>
                            <div class="clsProAction" ><a href="#" class="clsEUPro"><b>Edit</b></a>&nbsp;</div>
                    </div>
                    <div id="tabs" class="con-right-row4">
                        <ul>
                            <li><a href="#tabs-1">Messages</a></li>
                            <li><a href="#tabs-2">Comments</a></li>
                            <li><a href="#tabs-3">Photos</a></li>
                        </ul>

                  <!--  Thumb Box START-->
                                    <div id="tabs-1">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img" id="tabs-2">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                  <!--  Thumb Box START-->
                                    <div class="rg-thum-img" id="tabs-3">
                                        <div class="rg-thum-img-cel1"></div>
                                        <div class="rg-thum-iconbox">
                                            <div class="rg-thum-img-cel2"></div>
                                            <div class="rg-thum-img-cel3"></div>
                                            <div class="rg-thum-img-cel4">98% Liked</div>
                                        </div>
                                        <div class="rg-thum-content">
                                            <b>Rainbow Bar &nbsp; Grill</b><br />
                                            (626) 361-3642<br />
                                            709 N. La Brea Ave, CA 90038<br />
                                            One liner desciption of what the item is...
                                        </div>
                                    </div>
                  <!--  Thumb Box START-->
                    </div>
  <!-- Right part end  -->
                </div>
      		</div>
     	</div>
 <!--  Body END-->
<div class="blankdiv"></div>
