<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
echo "email address verified";
?>
<div style="height:130px;"></div>
    <div class="container" >
    <div class="con-box1" ><br/><br/><br/>
        <input type="hidden" name="msgInput" id="msgInput" value="<?php echo $this->emailVerify;?>"/>
       Hi marine_963@rediffmail.com, <p> Your email address is verified Please login to access Gopogo!
    </div>
    <div class="blankdiv"></div>
</div>