<?php
$this->title = "Login";
$this->headTitle($this->title);
//echo $this->form ;
//echo $this->msg;
?>


    <div style="height:110px;"></div>
    <!--  Body START-->
        <div class="container" >
            <div class="con-box" >

                <form id="forgot_form" name="forgot_form" method="post" action="">
                  <table height="112" border="1">
                    <tr>                      
                      <td width="300"><h1>Forgot Password</h1></td>
                      <td width="500"><?php echo $this->msg ?></td>
                    </tr>
                    <tr>                      
                      <td><strong>Email</strong></td>
                      <td><label>
                        <input type="text" name="email" size="100" />
                      </label></td>
                    </tr>
                    <tr>                      
                      <td align="center"><label>
                        <input type="submit" name="Submit" value="Forgot" />
                      </label></td>
                      <td><label>
                        <input type="reset" name="Submit2" value="Reset" />
                      </label></td>
                    </tr>
                  </table>
                </form>

             </div>
             <div class="blankdiv"></div>
        </div>