<?php
    // Create facebook object for facebook login functionality
    $facebook = Facebook_FbClass::getConfig();
?>
<div style="height:150px;"></div>
<!--  Body START-->
<div class="contenter" align="center">
    <div class="con-box" align="center">
        <!--Left Part start-->
        <div class="con-left">
                <div class="con-left-bg">
                <span class="accountLeftHeadTxt">Account</span>
                </div>

                <div class="accountSectionLightGrayBg">
                <span class="accountLeftSubTitleTxts">SIGN IN INFORMATION</span>
                </div>


                <!-- email update -->
                <div class="accountSectionInnerLayout">
                    <div class="emailPasswodUsernameHeadBg">
                        <div class="emailPasswodUsernameHeadText">Email: </div>
                    </div>
                    <div class="emailPasswodUsernamesBg">
                        <div class="emailPasswodUsernameText clsUpdateEmail"><?php echo $this->email;?></div>
                    </div>
                    <div class="emailPasswodUsernamesEdiBg">
                        <div class="emailPasswodUsernamesEditText clsUpdateAccUserEmailInfo"><a href="#" class="clsUpdateAccUserEmail"><b>edit</b></a></div>
                    </div>
                </div>
                <!-- password update -->
                <div class="accountSectionInnerLayout">
                    <div class="emailPasswodUsernameHeadBg">
                        <div class="emailPasswodUsernameHeadText clsUpdatePassTxt">Password: </div>
                    </div>
                    <div class="emailPasswodUsernamesBg">
                        <div class="emailPasswodUsernameText clsUpdatePass">*******</div>
                        <div class="clsResetPass"  style="display:none">
                        <div class="emailPasswodUsernameHeadTextNormal">Current Password:</div><div class="emailPasswodUsernameText"><input type="password" class="clsUpdateOldPass"/></div>
                        <div class="emailPasswodUsernameHeadTextNormal">New Password:</div><div class="emailPasswodUsernameText"><input type="password" class="clsUpdateNewPass"/></div>
                        <div class="emailPasswodUsernameHeadTextNormal">Re-Type New Password:</div><div class="emailPasswodUsernameText"><input type="password" class="clsUpdateConfirmPass"/></div>
                        </div>
                    </div>
                    <div class="emailPasswodUsernamesEdiBg">
                        <div class="emailPasswodUsernamesEditText clsUpdateAccUserPassInfo"><a href="#" class="clsUpdateAccUserPass"><b>edit</b></a></div>
                    </div>
                </div>

                <!-- username update -->
                <div class="accountSectionInnerLayout">
                    <div class="emailPasswodUsernameHeadBg">
                        <div class="emailPasswodUsernameHeadText">Username:</div>
                    </div>
                    <div class="emailPasswodUsernamesBg">
                        <div class="emailPasswodUsernameText clsUpdateUserName"><?php echo $this->userName;?>    </div>
                    </div>
                    <div class="emailPasswodUsernamesEdiBg">
                        <div class="emailPasswodUsernamesEditText clsUpdateAccUserNameInfo"><a href="#" class="clsUpdateAccUserName"><b>edit</b></a></div>
                    </div>
                </div>




                <div class="accountSectionLightGrayBg">
                <span class="accountLeftSubTitleTxts">PARTNER INFORMATION</span>
                </div>

                <div class="accountSectionInnerLayout">
                <div class="emailPasswodUsernameHeadBg">
                <div class="emailPasswodUsernameHeadText">Twitter:</div>
                <div class="emailPasswodUsernameHeadText">Facebook: </div>
                </div>
                 <div class="emailPasswodUsernamesBg">
                 <div class="emailPasswodUsernameText">@Becky</div>
                     <div class="emailPasswodUsernameText clsFbEmail">
                     <?php if($this->facebookName) { echo $this->facebookName; }
                           else if (empty($this->facebookName)) { echo $facebook->FBLogin(); }
                      ?>
                     </div>
                 </div>
                  <div class="emailPasswodUsernamesEdiBg">
                  <div class="emailPasswodUsernamesEditText">edit</div>

                  <div class="emailPasswodUsernamesEditText clsRmvFbUname">
                  <?php if(!empty($this->facebookName)) { ?><a href="#" >Remove</a> <?php } ?></div>
                  </div>
                </div>

        </div>
        <!--Left Part END-->
        <!-- Right part Start  -->
        <div class="con-right">
            <div class="accountSectionrightTopHeadBg">
            <div class="accountRightHeadTxt">Purchase History</div>
            <div class="haveAQuestionText">Have a Question?</div>
            </div>

            <div class="accountSectionrightDropDowndBg">
            <div class="dropDownBg">
            <div class="dropDownText">Orders placed in past 6 months</div>
            </div>
            </div>

            <div class="accountSectionBlueTitle">No Purchases Found.</div>
            <div class="accountSectionNormalText">Please select another date range.</div>
        </div>
    </div>
</div>

 