    <div style="height:150px;"></div>
    <!--  Body START-->
    <div class="contenter" align="center">
        <div class="con-box" align="center">
            <!--Left Part start-->
            <div class="con-left">
                <div class="con-left-bg">
                <span class="accountLeftHeadTxt">Account</span>
                </div>

                <div class="accountSectionLightGrayBg">
                    <span class="accountLeftSubTitleTxts">SIGN IN INFORMATION</span>
                </div>

                <div class="signinbox">

                        <div class="accountSectionInnerLayout">
                                <div class="accountSectionPasswordbg dsplfld-email">
                                        <div class="rowSectionBg">
                                                <div class="emailPasswodUsernameHeadTextNew">Email: </div>
                                                <div class="emailPasswodUsernameTextNew dsplUpdateEmail"><?php echo $this->email;?></div>
                                                <div class="updatebtn-text clsemail-update">                                                    
                                                    <a href="#">update</a>
                                                </div>
                                        </div>
                                </div>
                                <div class="emailbox d1">
                                        <div class="accountSectionPasswordbg">
                                                <div class="rowSectionBg">
                                                        <div class="emailPasswodUsernameHeadTextNew">Email*:</div>
                                                        <div class="emailPasswodUsernameTextNew"><input class="accountSectionInputBg inpclsUpdateEmail" type="text" /></div>
                                                </div>
                                        </div>
                                        <div class="accountSectionBottomButton">
                                                <div class="cancelbtn-text clsemail-cancel">
                                                        <a href="#">Cancel</a>
                                                </div>
                                                <div class="accountSectionBottomButtonBg save-email">
                                                        <a href="#"><img src="/themes/default/images/save-btn.png" border="0" /></a>                                                        
                                                </div>
                                        </div>
                                </div>
                        </div>

                        <div class="accountSectionInnerLayout">
                                <div class="accountSectionPasswordbg dsplfld-password">
                                        <div class="rowSectionBg">
                                                <div class="emailPasswodUsernameHeadTextNew">Password: </div>
                                                <div class="emailPasswodUsernameTextNew dsplUpdatePassword">************</div>
                                                <div class="updatebtn-text clspassword-update"><a href="#">update</a></div>
                                        </div>
                                </div>
                                <div class="passwordbox d1">
                                        <div class="accountSectionPasswordbg">
                                                <div class="rowSectionBg">
                                                        <div class="emailPasswodUsernameHeadTextNew">Old Password*:</div>
                                                        <div class="emailPasswodUsernameTextNew"><input class="accountSectionInputBg inpclsUpdateOldPassword" type="password" /></div>
                                                </div>
                                                <div class="rowSectionBg">
                                                        <div class="emailPasswodUsernameHeadTextNew">New Password*:</div>
                                                        <div class="emailPasswodUsernameTextNew"><input class="accountSectionInputBg inpclsUpdateNewPassword" type="password" /></div>
                                                </div>
                                                <div class="rowSectionBg">
                                                        <div class="emailPasswodUsernameHeadTextNew">Re-type New Password*:</div>
                                                        <div class="emailPasswodUsernameTextNew"><input class="accountSectionInputBg inpclsUpdateConfirmNewPassword" type="password" /></div>
                                                </div>
                                        </div>
                                        <div class="accountSectionBottomButton">
                                                <div class="cancelbtn-text clsepassword-cancel"><a href="#">Cancel</a></div>
                                                <div class="accountSectionBottomButtonBg save-password">
                                                        <a href="#"><img src="/themes/default/images/save-btn.png" border="0" /></a>
                                                </div>
                                        </div>
                                </div>
                        </div>

                        <div class="accountSectionInnerLayout">
                                <div class="accountSectionPasswordbg dsplfld-username">
                                        <div class="rowSectionBg">
                                                <div class="emailPasswodUsernameHeadTextNew">Username: </div>
                                                <div class="emailPasswodUsernameTextNew dsplUpdateUsername"><?php echo $this->userName;?></div>
                                                <div class="updatebtn-text clsusername-update"><a href="#">update</a></div>
                                        </div>
                                </div>
                                <div class="usernamebox d1">
                                        <div class="accountSectionPasswordbg">
                                                <div class="rowSectionBg">
                                                        <div class="emailPasswodUsernameHeadTextNew">Username*:</div>
                                                        <div class="emailPasswodUsernameTextNew"><input class="accountSectionInputBg inpclsUpdateUsername" type="text" /></div>
                                                </div>
                                        </div>
                                        <div class="accountSectionBottomButton">
                                                <div class="cancelbtn-text clseusername-cancel"><a href="#">Cancel</a></div>
                                                <div class="accountSectionBottomButtonBg save-username">
                                                        <a href="#"><img src="/themes/default/images/save-btn.png" border="0" /></a>
                                                </div>
                                        </div>
                                </div>
                        </div>

                </div>



                <?php
                /*
                <!-- email update -->
                <div class="accountSectionInnerLayout">
                    <div class="emailPasswodUsernameHeadBg">
                        <div class="emailPasswodUsernameHeadText">Email: </div>
                    </div>
                    <div class="emailPasswodUsernamesBg">
                        <div class="emailPasswodUsernameText clsUpdateEmail"><?php echo $this->email;?></div>
                    </div>
                    <div class="emailPasswodUsernamesEdiBg">
                        <div class="emailPasswodUsernamesEditText clsUpdateAccUserEmailInfo"><a href="#" class="clsUpdateAccUserEmail"><b>edit</b></a></div>
                    </div>
                </div>
                <!-- password update -->
                <div class="accountSectionInnerLayout">
                    <div class="emailPasswodUsernameHeadBg">
                        <div class="emailPasswodUsernameHeadText clsUpdatePassTxt">Password: </div>
                    </div>
                    <div class="emailPasswodUsernamesBg">
                        <div class="emailPasswodUsernameText clsUpdatePass">*******</div>
                        <div class="clsResetPass"  style="display:none">
                        <div class="emailPasswodUsernameHeadTextNormal">Current Password:</div><div class="emailPasswodUsernameText"><input type="password" class="clsUpdateOldPass"/></div>
                        <div class="emailPasswodUsernameHeadTextNormal">New Password:</div><div class="emailPasswodUsernameText"><input type="password" class="clsUpdateNewPass"/></div>
                        <div class="emailPasswodUsernameHeadTextNormal">Re-Type New Password:</div><div class="emailPasswodUsernameText"><input type="password" class="clsUpdateConfirmPass"/></div>
                        </div>
                    </div>
                    <div class="emailPasswodUsernamesEdiBg">
                        <div class="emailPasswodUsernamesEditText clsUpdateAccUserPassInfo"><a href="#" class="clsUpdateAccUserPass"><b>edit</b></a></div>
                    </div>
                </div>

                <!-- username update -->
                <div class="accountSectionInnerLayout">
                    <div class="emailPasswodUsernameHeadBg">
                        <div class="emailPasswodUsernameHeadText">Username:</div>
                    </div>
                    <div class="emailPasswodUsernamesBg">
                        <div class="emailPasswodUsernameText clsUpdateUserName"><?php echo $this->userName;?>    </div>
                    </div>
                    <div class="emailPasswodUsernamesEdiBg">
                        <div class="emailPasswodUsernamesEditText clsUpdateAccUserNameInfo"><a href="#" class="clsUpdateAccUserName"><b>edit</b></a></div>
                    </div>
                </div>

                */
                ?>



                <div class="accountSectionLightGrayBg">
                    <span class="accountLeftSubTitleTxts">PARTNER INFORMATION</span>
                </div>

                <div class="partnerbox">

                    <?php
                    // for twitter
                    // partners
                    if(!empty($this->partners) && is_array($this->partners) && count($this->partners)>0 && !empty($this->partners[2]))
                    {
                    ?>
                    <div class="accountSectionInnerLayout twitterBox1 d2">
                        <div class="accountSectionPasswordbg">
                            <div class="rowSectionBg">
                                <div class="emailPasswodUsernameHeadTextNew">Twitter: </div>
                                <div class="emailPasswodUsernameTextNew2 dsplUpdateTwitter">@<?php echo $this->partners[2]['account_username']; ?></div>
                                <div class="connectbtn-text remove-twitter">
                                    <a href="#">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="accountSectionInnerLayout twitterBox2 d1">
                        <div class="accountSectionPasswordbg">
                            <div class="rowSectionBg">
                                <div class="emailPasswodUsernameHeadTextNew">Twitter: </div>
                                <div class="emailPasswodUsernameTextNew2 ">
                                    <div class="">
                                        <a href="#"><input type="button" value="Connect with Twitter" id="twitter-connect" /></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } else { ?>
                    <div class="accountSectionInnerLayout twitterBox1 d1">
                        <div class="accountSectionPasswordbg">
                            <div class="rowSectionBg">
                                <div class="emailPasswodUsernameHeadTextNew">Twitter: </div>
                                <div class="emailPasswodUsernameTextNew2 dsplUpdateTwitter">&nbsp;</div>
                                <div class="connectbtn-text remove-twitter">
                                    <a href="#">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="accountSectionInnerLayout twitterBox2 d2">
                        <div class="accountSectionPasswordbg">
                            <div class="rowSectionBg">
                                <div class="emailPasswodUsernameHeadTextNew">Twitter: </div>
                                <div class="emailPasswodUsernameTextNew2 ">
                                    <div class="">
                                        <a href="#"><input type="button" value="Connect with Twitter" id="twitter-connect" /></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>


                    <?php
                    // for facebook
                    // partners
                    if(!empty($this->partners) && is_array($this->partners) && count($this->partners)>0 && !empty($this->partners[1]))
                    {
                    ?>
                    <div class="accountSectionInnerLayout facebookBox1 d2">
                        <div class="accountSectionPasswordbg">
                            <div class="rowSectionBg">
                                <div class="emailPasswodUsernameHeadTextNew">Facebook: </div>
                                <div class="emailPasswodUsernameTextNew2 dsplUpdateFacebook"><?php echo $this->partners[1]['account_username']; ?></div>
                                <div class="connectbtn-text remove-facebook">
                                    <a href="#">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="accountSectionInnerLayout facebookBox2 d1">
                        <div class="accountSectionPasswordbg">
                            <div class="rowSectionBg">
                                <div class="emailPasswodUsernameHeadTextNew">Facebook: </div>
                                <div class="emailPasswodUsernameTextNew2 ">
                                    <div class=" ">
                                        <a href="#"><input type="button" value="Connect with Facebook" id="facebook-connect" /></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } else { ?>
                    <div class="accountSectionInnerLayout facebookBox1 d1">
                        <div class="accountSectionPasswordbg">
                            <div class="rowSectionBg">
                                <div class="emailPasswodUsernameHeadTextNew">Facebook: </div>
                                <div class="emailPasswodUsernameTextNew2 dsplUpdateFacebook">pqr</div>
                                <div class="connectbtn-text remove-facebook">
                                    <a href="#">Remove</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="accountSectionInnerLayout facebookBox2 d2">
                        <div class="accountSectionPasswordbg">
                            <div class="rowSectionBg">
                                <div class="emailPasswodUsernameHeadTextNew">Facebook: </div>
                                <div class="emailPasswodUsernameTextNew2 ">
                                    <div class=" ">
                                        <a href="#"><input type="button" value="Connect with Facebook" id="facebook-connect" /></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>



                </div>

                <?php
                /*
                <div class="accountSectionInnerLayout">
                <div class="emailPasswodUsernameHeadBg">
                <div class="emailPasswodUsernameHeadText">Twitter:</div>
                <div class="emailPasswodUsernameHeadText">Facebook: </div>
                </div>
                 <div class="emailPasswodUsernamesBg">
                 <div class="emailPasswodUsernameText">@Becky</div>
                 <div class="emailPasswodUsernameText">Becky Denson</div>
                 </div>
                  <div class="emailPasswodUsernamesEdiBg">
                  <div class="emailPasswodUsernamesEditText">edit</div>
                  <div class="emailPasswodUsernamesEditText">edit</div>
                  </div>
                </div>
                */
                ?>
        </div>
        <!--Left Part END-->
        <!-- Right part Start  -->
        <div class="con-right">
            <div class="accountSectionrightTopHeadBg">
            <div class="accountRightHeadTxt">Purchase History</div>
            <div class="haveAQuestionText">Have a Question?</div>
            </div>

            <div class="accountSectionrightDropDowndBg">
            <div class="dropDownBg">
            <div class="dropDownText">Orders placed in past 6 months</div>
            </div>
            </div>

            <div class="accountSectionBlueTitle">No Purchases Found.</div>
            <div class="accountSectionNormalText">Please select another date range.</div>
        </div>
           
        <div class="blankdiv"></div>
        <div class="blankdiv"></div>
    </div>

</div>

 