<?php
$loginFlag = false;
$fbLogin = "false";
$session = GP_GPAuth::getSession();
if(!empty($session) && !empty($session->user_id) && $session->user_id>0)
    {
        $loginFlag = true;
        $user_name = $session->user_name;
        $fbLogin = "true";
    }
else {
        // create facebook object
        $facebook = Facebook_FbClass::getConfig();
    }
?>
<!--Sign in START-->
            <div  id="loginBox" >
                <div class="create-ac-head" >
                    <div class="sign-in-leftbg"></div>
                    <div class="sign-in-middlebg">
                    	<div class="create-ac-head-txt">Sign in to <b>GoPogo</b></div>
                    </div>
                    <div class="sign-in-rightbg"></div>
                    <div class="login-close" ></div>
                </div>
                <div class="sign-in-centerbg" id="sign-in-centerbg">
                        <form action=""  id="loginBoxForm" name="loginBoxForm" method="post">
                        <div class="sign-in-right">
                            <div class="create-ac-input1"><input type="text" value="Email Address" maxlength="50" onclick="if(this.value=='Email Address') {this.value = ''; $().setTextColor(this); }else if(this.value == ''){ $().removeTextColor(this);}" onblur="if(this.value=='') {this.value = 'Email Address'; $().removeTextColor(this);} else if(this.value == 'Email Address'){ $().removeTextColor(this); } else {$().setTextColor(this);}" onkeypress="if(this.value=='Email Address') {this.value = '';$().removeTextColor(this);}else{$().setTextColor(this);}" name="email" id="email" class="clsSignInEmail"/></div>
                            <div class="create-ac-input2">
                                <input type="text" maxlength="50" onfocus="$('.clsSignInPwdOld').attr('style','display:none');$('.clsSignInPwd').removeAttr('style');$('.clsSignInPwd').focus()" value="Password" name="passwdOld" id="passwdOld" class="clsSignInPwdOld"/>
                                <input type="password" maxlength="50" onfocus="$().setTextColor(this);" onblur="if(this.value=='') { $('.clsSignInPwdOld').removeAttr('style');$('.clsSignInPwd').attr('style','display:none');}" style="display: none;" value=""  name="passwd" id="passwd" class="clsSignInPwd"/>
                            </div>
                            <div class="sign-in-input3">
                                    <span class="sign-in-txt"><?php echo $this->mess; ?>Forgot your</span>
                                    <a href="#" onclick="return false;" class="sign-in-create-account clsForgot" id="forgotPassword" >password</a>
                                    <span>or</span>
                                    <a href="#" onclick="return false;" class="clsSignUp sign-in-create-account createAccount">create account</a>
                            </div>
                            <a  href="#" class="sign-in-button clsLoginSubmitBox" id="loginSubmitBox"></a>
                            <div class="sign-in-input4">
                                  <?php  if($fbLogin == "false") { echo $facebook->FBLogin(); } ?>
                             </div>
                        </div>
                       </form>
                </div>
                <div class="sign-in-bottombg"></div>
            </div>
<!--Sign in END-->