<?php
    $session = GP_GPAuth::getSession();    
    $loginFlag = false;
    $user_name = '';
    if(!empty($session) && !empty($session->user_id) && $session->user_id>0)
    {
        $loginFlag = true;
        $user_name = $session->user_name;
    }
    
?>

<div style="height:130px;"></div>    
    <div class="container" >
    <div class="con-box1" ><br/><br/><br/>
       Hi <?php echo ucfirst($user_name) ?>, Welcome to GoPogo!
    </div>
    <div class="blankdiv"></div>
</div>
