<!--
<br /><br /><center>View script for controller <b>Account</b> and script/action name <b>signup</b></center>
-->
<?php
$this->title = "Signup";
$this->headTitle($this->title);
//echo $this->form ;
//echo $this->msg;
?>

    <div style="height:110px;"></div>
    <!--  Body START-->
        <div class="container" >
            <div class="con-box" >

                <form id="signup_form" name="signup_form" method="post" action="">
                  <table width="961" height="112" border="1">
                    <tr>
                      <th scope="row">&nbsp;</th>
                      <td><h1>Signup</h1></td>
                      <td><?php echo $this->msg ?></td>
                    </tr>
                    <tr>
                      <th scope="row">&nbsp;</th>
                      <td><strong>Email</strong></td>
                      <td><label>
                        <input type="text" name="email" />
                      </label></td>
                    </tr>
                    <tr>
                      <th scope="row">&nbsp;</th>
                      <td><strong>Password</strong></td>
                      <td><label>
                        <input type="password" name="passwd" />
                      </label></td>
                    </tr>
                            <tr>
                      <th scope="row">&nbsp;</th>
                      <td><strong>Retype Password</strong></td>
                      <td><label>
                        <input type="password" name="retype_passwd" />
                      </label></td>
                    </tr>
                    <tr>
                      <th scope="row">&nbsp;</th>
                      <td align="center"><label>
                        <input type="submit" name="Submit" value="Signup" />
                      </label></td>
                      <td><label>
                        <input type="reset" name="Submit2" value="Reset" />
                      </label></td>
                    </tr>
                  </table>
                </form>
                <?php
                //echo phpinfo();
                ?>
                
             </div>
             <div class="blankdiv"></div>
        </div>
